"""empty message

Revision ID: 587198086c79
Revises: d86701ba7f86
Create Date: 2020-10-07 19:59:18.501017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587198086c79'
down_revision = 'd86701ba7f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_artist',
    sa.Column('venue_id', sa.Integer(), nullable=True, peimary_key=True),
    sa.Column('artist_id', sa.Integer(), nullable=True, peimary_key=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_artist')
    # ### end Alembic commands ###
