"""empty message

Revision ID: 920fb8eedfcb
Revises: 2be83a706570
Create Date: 2020-10-08 23:03:34.300380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920fb8eedfcb'
down_revision = '2be83a706570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.add_column('Artist', sa.Column('seeking', sa.CHAR(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking', sa.CHAR(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking')
    # ### end Alembic commands ###
